version: '3'

services:
  web:
    build: .
    command: gunicorn blog_prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/user/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data: